apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis
  namespace: demoproject
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Mi
  hostPath:
    path: /data/redis/

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  namespace: demoproject
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
  volumeName: redis
